uploads = []
outputs = []

[[generated]]
id = "uAWYTNYKTa62jTprrHFo0"
uri = "file://artifacts/royal/src/assets/images/salon.png"
type = "image"
title = "Classic elegance salon"

[[generated]]
id = "oMTv_yWOEtkRZsEW0kbKK"
uri = "file://artifacts/royal/src/assets/images/table.png"
type = "image"
title = "Nova dining table"

[[generated]]
id = "NjHi9U1pnx6BY3aeubnEn"
uri = "file://artifacts/royal/src/assets/images/fauteuil.png"
type = "image"
title = "Prestige armchair"

[[generated]]
id = "z55jq-jC2LpehHXb1s_gI"
uri = "file://artifacts/royal/src/assets/images/enfant.png"
type = "image"
title = "Star kids room"

[[generated]]
id = "hqRXglDxXgzbfLmfpdxl6"
uri = "file://artifacts/royal/src/assets/images/princesse.png"
type = "image"
title = "Princess bedroom"

[[generated]]
id = "FSnLFtsD3XfowfVE-xB1_"
uri = "file://artifacts/royal/src/assets/images/miroir.png"
type = "image"
title = "Royal mirror"
